### ISSUE TITLE
HTTP Error 404 on Stylus

### ISSUE THREAD

**Issue by hiyorijl** [rubyowo/chatgpt#2]
it appears "HTTP Error 404" and doesn't let me install theme on Stylus when I click it, please fix :''3

**Comment by rubyowo** [comment]
@hiyorijl the theme is waiting to be upstreamed into the catppuccin org.
In the mean time please use [this link](https://github.com/rubyowo/chatgpt/blob/master/catppuccin.user.css?raw=1) to install it.
