### ISSUE TITLE
Sidebar button color could be fixed

### ISSUE THREAD

**Issue by skelebro1** [rubyowo/chatgpt#3]
here's the issue:-
![image](https://user-images.githubusercontent.com/115771640/235355915-c11db57d-5b71-4f6e-ad40-d153e1fb3898.png)

this could be fixed with just few lines
```
.px-3 {
    background: var(--ctp-mantle)
}

.px-3:hover {
    background: var(--ctp-base)
```
thanks!

**Comment by rubyowo** [comment]
ah. thanks
